### ISSUE TITLE
Support "tags" field when creating/updating recipients

### ISSUE THREAD

**Issue by winklr** [rapidmail/rapidmail-apiv3-client-php#9]
When creating or updating recipients for a specific recipients list, updating recipient's **tags** should be possible.
The following code returns 422:

```php 
$recipientsService = $client->recipients();
$recipientsService->create(
  array(
    'recipientlist_id' => 1234, // some existing list id
    'email' => 'test@test.com',
    'firstname' => 'Firstname',
    'lastname' => 'Lastname',
    'tags' => array('some_tag')
));
```
Response:
```"API error 422 when requesting https://apiv3.emailsys.net/v1/recipients. Detail: {\"type\":\"http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html\",\"title\":\"Unprocessable Entity\",\"status\":422,\"detail\":\"Unrecognized fields: tags\"}"```

When submitting forms created in Rapidmail (using html embed code), tags are supported, though.

**Comment by eth8505** [comment]
This is nothing we can actually do in the client itself, as the API itself does not support the feature. The client already correctly passes the list of tags to the API, which is why the error message "Unrecognized fields: tags" is generated by the server.

I relayed your request internally. However, I can't make any promises on how long it might take for this to be implemented.

Currently, tags can be set for recipients by
1. creating or editing a recipient manually in rapidmail
2. importing a CSV, either via rapidmail or using the [RecipientImport API endpoint](https://developer.rapidmail.wiki/documentation.html?urls.primaryName=Recipients#/RecipientImport/post_recipients_import)
3. Adding recipients using one of our forms

Please note, that our subscription forms do not use the developer API with a different feature set.

I will close this task, as the feature request relates to the API itself rather than this API client. Please feel free to contact our customer support if you have any further questions.
